import fs from 'node:fs'
import path from 'node:path'

const TARGET_WIDTHS = [640, 1280, 1920] as const

export interface ImageVariant {
  src: string
  width: number
}

export interface OptimizedImage {
  variants: ImageVariant[]
  fullSrc: string | null
}

/**
 * Maps an original image URL to its optimized WebP base path.
 * Handles relative paths (/img/..., /uploads/img/original/...) and
 * absolute Strapi URLs (http://host/uploads/...).
 * Returns null for SVGs or unrecognized paths.
 */
function getOptimizedBase(src: string): string | null {
  if (!src || src.endsWith('.svg')) return null

  let pathname = src
  if (src.startsWith('http')) {
    try {
      pathname = new URL(src).pathname
    } catch {
      return null
    }
  }

  const ext = path.extname(pathname)
  if (!ext) return null
  const stem = pathname.slice(0, -ext.length)

  if (pathname.startsWith('/uploads/img/original/')) {
    return `/img/optimized/uploads${stem.slice('/uploads/img/original'.length)}`
  }

  if (pathname.startsWith('/img/') && !pathname.startsWith('/img/optimized/')) {
    return `/img/optimized${stem.slice('/img'.length)}`
  }

  return null
}

/**
 * Returns available optimized WebP data for an image, checking the filesystem
 * to confirm variants were actually generated by the optimization script.
 *
 * Returns responsive `variants` (sized at target widths) plus a `fullSrc`
 * WebP at the original dimensions. For images smaller than the smallest
 * target width, only `fullSrc` will be populated.
 *
 * Safe to call at build time (Astro static output).
 */
export function getOptimizedImage(src: string): OptimizedImage {
  const base = getOptimizedBase(src)
  if (!base) return { variants: [], fullSrc: null }

  const publicDir = path.join(process.cwd(), 'public')

  const variants = TARGET_WIDTHS.filter((w) =>
    fs.existsSync(path.join(publicDir, `${base}-${w}.webp`))
  ).map((w) => ({
    src: `${base}-${w}.webp`,
    width: w,
  }))

  const fullWebP = `${base}-full.webp`
  const fullSrc = fs.existsSync(path.join(publicDir, fullWebP))
    ? fullWebP
    : null

  return { variants, fullSrc }
}
