import { describe, expect, it } from 'vitest'
import { TARGET_WIDTHS } from '@/utils/main/imagePaths'
import { planVariants } from './variantPlan'

describe('planVariants', () => {
  it('emits every target width the source can fill, plus its intrinsic width', () => {
    const plan = planVariants('hero', 1200, TARGET_WIDTHS)

    expect(plan.widths).toEqual([640, 1200])
    expect(plan.variants).toEqual([
      { fileName: 'hero-640.webp', format: 'webp', width: 640 },
      { fileName: 'hero-640.avif', format: 'avif', width: 640 },
      { fileName: 'hero-1200.webp', format: 'webp', width: 1200 },
      { fileName: 'hero-1200.avif', format: 'avif', width: 1200 }
    ])
  })

  it('writes no separate full-size pair — the widest variant is the full-size one', () => {
    // resize(intrinsicWidth) is a no-op, so a `-full` output was byte-identical
    // to `-<intrinsicWidth>`: ~31% of generated bytes, ~35% of encode time.
    const plan = planVariants('hero', 1200, TARGET_WIDTHS)

    expect(plan.variants.map((v) => v.fileName)).not.toContain('hero-full.webp')
    expect(plan.variants.every((v) => Number.isInteger(v.width))).toBe(true)
    expect(plan.variants.at(-1)).toEqual({
      fileName: 'hero-1200.avif',
      format: 'avif',
      width: 1200
    })
  })

  it('always encodes the intrinsic width so the widest variant is never upscaled', () => {
    for (const intrinsic of [400, 1200, 4000]) {
      const plan = planVariants('x', intrinsic, TARGET_WIDTHS)
      expect(plan.widths.at(-1)).toBe(intrinsic)
    }
  })

  it('does not duplicate the intrinsic width when it is already a target', () => {
    const plan = planVariants('hero', 1280, TARGET_WIDTHS)

    expect(plan.widths).toEqual([640, 1280])
  })

  it('never upscales past the intrinsic width', () => {
    const plan = planVariants('icon', 400, TARGET_WIDTHS)

    expect(plan.widths).toEqual([400])
    expect(plan.variants.map((v) => v.fileName)).toEqual([
      'icon-400.webp',
      'icon-400.avif'
    ])
  })

  it('keeps widths ascending for a source wider than every target', () => {
    const plan = planVariants('wide', 4000, TARGET_WIDTHS)

    expect(plan.widths).toEqual([640, 1280, 1920, 2560, 3840, 4000])
  })

  it('plans nothing when the intrinsic width is unknown or nonsensical', () => {
    for (const width of [0, -1]) {
      expect(planVariants('broken', width, TARGET_WIDTHS)).toEqual({
        widths: [],
        variants: []
      })
    }
  })

  it('emits both formats at every width', () => {
    const plan = planVariants('hero', 1200, TARGET_WIDTHS)

    for (const width of plan.widths) {
      expect(plan.variants.filter((v) => v.width === width)).toHaveLength(2)
    }
    expect(plan.variants).toHaveLength(plan.widths.length * 2)
  })

  it('keeps dots and dashes in the source name', () => {
    const plan = planVariants('logo.dark-2x', 500, [])

    expect(plan.variants.map((v) => v.fileName)).toEqual([
      'logo.dark-2x-500.webp',
      'logo.dark-2x-500.avif'
    ])
  })
})
