import type { VariantFormat } from './ports'

export const VARIANT_FORMATS: readonly VariantFormat[] = ['webp', 'avif']

export interface PlannedVariant {
  fileName: string
  format: VariantFormat
  width: number
}

export interface VariantPlan {
  /** Widths to emit, ascending. */
  widths: number[]
  variants: PlannedVariant[]
}

/**
 * Decides which files an image should produce. Pure — no filesystem, no
 * encoder — so the naming and width rules can be asserted directly.
 *
 * There is deliberately no separate full-size output. Because the intrinsic
 * width is always in the width set, `resize(intrinsicWidth)` is a no-op and the
 * old `-full` pair was byte-identical to `-<intrinsicWidth>` for every source —
 * ~31% of generated bytes and ~35% of encode time spent writing duplicates.
 * The largest numbered variant is the full-size one.
 */
export function planVariants(
  baseName: string,
  intrinsicWidth: number,
  targetWidths: readonly number[]
): VariantPlan {
  if (intrinsicWidth <= 0) return { widths: [], variants: [] }

  const widths = resolveWidths(intrinsicWidth, targetWidths)
  return {
    widths,
    variants: widths.flatMap((width) => formatPair(baseName, width))
  }
}

/**
 * Target widths the source can actually fill, plus its intrinsic width.
 *
 * The intrinsic width is always emitted even when it isn't a target: otherwise
 * a 1200px original only gets 640 (+ full), and responsive srcsets that omit
 * `-full` force the browser to upscale 640 on desktop (INTORG-934).
 */
function resolveWidths(
  intrinsicWidth: number,
  targetWidths: readonly number[]
): number[] {
  const widths = new Set(targetWidths.filter((w) => w <= intrinsicWidth))
  widths.add(intrinsicWidth)
  return [...widths].sort((a, b) => a - b)
}

function formatPair(baseName: string, width: number): PlannedVariant[] {
  return VARIANT_FORMATS.map((format) => ({
    fileName: `${baseName}-${width}.${format}`,
    format,
    width
  }))
}
