import fs from 'node:fs'
import path from 'node:path'

export const TARGET_WIDTHS = [640, 1280, 1920, 2560, 3840] as const

export const IMAGE_URL_PATHS = {
  publicSource: '/img',
  publicOptimized: '/img/optimized',
  uploadSource: '/uploads/img/original',
  uploadOptimized: '/img/optimized/uploads'
} as const

export interface ImageVariant {
  src: string
  width: number
}

export interface OptimizedImage {
  variants: ImageVariant[]
  fullSrc: string | null
  avifVariants: ImageVariant[]
  avifFullSrc: string | null
}

export function buildImageSrcset(variants: ImageVariant[]): string {
  return variants.map((v) => `${v.src} ${v.width}w`).join(', ')
}

export function hasOptimizedVariants(image: OptimizedImage): boolean {
  return image.variants.length > 0 || image.fullSrc !== null
}

export function pathToSegments(urlPath: string): string[] {
  return urlPath.split('/').filter(Boolean)
}

function isWithinUrlPath(pathname: string, basePath: string): boolean {
  return pathname === basePath || pathname.startsWith(`${basePath}/`)
}

function replaceUrlPathPrefix(
  pathname: string,
  fromPath: string,
  toPath: string
): string {
  return `${toPath}${pathname.slice(fromPath.length)}`
}

/**
 * Maps an original image URL to its optimized WebP base path.
 * Handles relative paths (/img/..., /uploads/img/original/...) and
 * absolute Strapi URLs (http://host/uploads/...).
 * Returns null for SVGs or unrecognized paths.
 */
function getOptimizedBase(src: string): string | null {
  if (!src || src.endsWith('.svg')) return null

  let pathname = src
  if (src.startsWith('http')) {
    try {
      pathname = new URL(src).pathname
    } catch {
      return null
    }
  }

  const ext = path.extname(pathname)
  if (!ext) return null
  const stem = pathname.slice(0, -ext.length)

  if (isWithinUrlPath(pathname, IMAGE_URL_PATHS.uploadSource)) {
    return replaceUrlPathPrefix(
      stem,
      IMAGE_URL_PATHS.uploadSource,
      IMAGE_URL_PATHS.uploadOptimized
    )
  }

  if (
    isWithinUrlPath(pathname, IMAGE_URL_PATHS.publicSource) &&
    !isWithinUrlPath(pathname, IMAGE_URL_PATHS.publicOptimized)
  ) {
    return replaceUrlPathPrefix(
      stem,
      IMAGE_URL_PATHS.publicSource,
      IMAGE_URL_PATHS.publicOptimized
    )
  }

  return null
}

/**
 * Returns available optimized WebP data for an image, checking the filesystem
 * to confirm variants were actually generated by the optimization script.
 *
 * Returns responsive `variants` (sized at target widths) plus a `fullSrc`
 * WebP at the original dimensions. For images smaller than the smallest
 * target width, only `fullSrc` will be populated.
 *
 * Safe to call at build time (Astro static output).
 */
export function getOptimizedImage(src: string): OptimizedImage {
  const base = getOptimizedBase(src)
  if (!base) {
    return { variants: [], fullSrc: null, avifVariants: [], avifFullSrc: null }
  }

  const publicDir = path.join(process.cwd(), 'public')
  const exists = (rel: string) => fs.existsSync(path.join(publicDir, rel))

  const variants = TARGET_WIDTHS.filter((w) => exists(`${base}-${w}.webp`)).map(
    (w) => ({ src: `${base}-${w}.webp`, width: w })
  )

  const avifVariants = TARGET_WIDTHS.filter((w) =>
    exists(`${base}-${w}.avif`)
  ).map((w) => ({ src: `${base}-${w}.avif`, width: w }))

  const fullWebP = `${base}-full.webp`
  const fullAvif = `${base}-full.avif`

  return {
    variants,
    fullSrc: exists(fullWebP) ? fullWebP : null,
    avifVariants,
    avifFullSrc: exists(fullAvif) ? fullAvif : null
  }
}
