name: PR Checks

on:
  pull_request:
      branches:
        - staging
        - playground

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4

      - name: Install CMS dependencies
        working-directory: cms
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run unit tests
        working-directory: cms
        run: pnpm test

  build-and-dryrun:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'playground' && 'strapi-playground' || 'strapi-staging' }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Cache optimized images
        uses: actions/cache@v4
        with:
          path: public/img/optimized
          key: optimized-images-${{ github.run_id }}
          restore-keys: |
            optimized-images-

      - name: Build and Dry Run
        env:
          STRAPI_API_TOKEN: ${{ secrets.ENV_STRAPI_TOKEN_DRY_RUN }}
          STRAPI_URL: ${{ vars.ENV_STRAPI_URL }}
        run: |
          # Fail fast if STRAPI_API_TOKEN or STRAPI_URL are not set
          if [ -z "$STRAPI_API_TOKEN" ]; then
            echo "Error: STRAPI_API_TOKEN is not set."
            exit 1
          fi

          if [ -z "$STRAPI_URL" ]; then
            echo "Error: STRAPI_URL is not set."
            exit 1
          fi

          pnpm install --frozen-lockfile      
          pnpm run build
          cd cms
          pnpm install --frozen-lockfile
          pnpm run build
          echo "Running MDX sync in dry-run mode against ${STRAPI_URL}"
          # To help with debugging, we will hash the contents of the STRAPI_API_TOKEN
          # and output it here so that we can verify that the correct token is used without exposing
          # the actual value in the logs.
          echo "STRAPI_API_TOKEN hash: $(echo -n $STRAPI_API_TOKEN | sha256sum)"
          pnpm run sync:mdx:dry-run
